library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app'

urlpatterns = [
    path('', views.UnitsList.as_view(), name='index'),
    path('add/', views.UnitsAdd.as_view(), name='units_add'),
    path('content/<int:pk>/', views.UnitsDetail.as_view(), name='units_detail'),
    ]

tellcapProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

library_app/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class UnitChildModel(models.Model):

    title = models.CharField(default='', max_length=250)
    description = RichTextField(verbose_name='Описание', blank=True)
    is_active = models.BooleanField(db_index=True, verbose_name='Активна', default=True)
    #author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    #created = models.DateField(verbose_name='Дата создания', auto_created=True, null=False)

    def __str__(self):
        return f'{self.title}'


class UnitMainModel(models.Model):

    class Meta:
        verbose_name = 'Модуль'
        verbose_name_plural = 'Модули'

    title = models.CharField(default='', max_length=250)
    context = models.ManyToManyField(UnitChildModel)

library_app/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.forms import Textarea

from library_app.models import UnitChildModel


class UnitsAddForm(forms.ModelForm):
    # description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = UnitChildModel
        fields = ['title', 'description', 'is_active']
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 40}),
        }

library_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView

from library_app.forms import UnitsAddForm
from library_app.models import UnitMainModel, UnitChildModel


# Create your views here.

class UnitsList(ListView):
    model = UnitChildModel



class UnitsAdd(CreateView):
    model = UnitChildModel
    form_class = UnitsAddForm
    success_url = reverse_lazy('library_app:index')


class UnitsDetail(DetailView):
    model = UnitChildModel

library_app/templates/library_app/unitchildmodel_detail.html
{% extends 'library_app/main.html' %}
{% load static %}

{% block content %}

    <div>{{ object.parent_category }}</div>
    <div>{{ object.title }}</div>
    <div>{{ object.description | safe }}</div>
    <div>{{ object.is_active }}</div>

{% endblock %}

library_app/templates/library_app/unitchildmodel_form.html
{% extends 'library_app/main.html' %}
{% load static %}

{% block content %}
    <form method="post" action="{% url 'library_app:units_add' %}">
        {% csrf_token %}
        <div>{{ form.parent_category }}</div>
        <div>{{form.title}}</div>
        <div>{{ form.description }}</div>
        <div>{{ form.is_active }}</div>
        <div class="row action-buttons">
                <div class="col-12 col-md-auto">
                    <button type="submit"
                            class="submit-button btn btn-primary btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1"
                            data-loading-text="Loading...">
                        <i class="bx bx-save text-4 me-2"></i> Сохранить
                    </button>
                </div>
                <div class="col-12 col-md-auto px-md-0 mt-3 mt-md-0">
                    <a href="{% url 'library_app:index' %}"
                       class="cancel-button btn btn-light btn-px-4 py-3 border font-weight-semibold text-color-dark text-3">Отменить</a>
                </div>
                <div class="col-12 col-md-auto ms-md-auto mt-3 mt-md-0 ms-auto">
                    <a href="#"
                       class="delete-button btn btn-danger btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1">
                        <i class="bx bx-trash text-4 me-2"></i> Удалить
                    </a>
                </div>
            </div>
    </form>

{% endblock %}

library_app/templates/library_app/unitchildmodel_list.html
{% extends 'library_app/main.html' %}
{% load static %}

{% block content %}

        <div class="recent_event_area section__padding">
            <div class="container">
                {% for item in object_list %}
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="single_event d-flex align-items-center">

                            <div class="event_info">
                                <a href="{% url 'library_app:units_detail' item.pk %}">
                                    <h4>{{ item.title }}</h4>
                                </a>
                                <p><span> <i class="flaticon-clock"></i> 10:30 pm</span> <span> <i
                                        class="flaticon-calendar"></i> 21Nov 2020 </span> <span> <i
                                        class="flaticon-placeholder"></i> AH Oditoriam</span></p>
                            </div>
                        </div>
                    </div>
                </div>
               {% endfor %}
            </div>
        </div>

{% endblock %}

library_app/templates/library_app/unitmodel_detail.html
{% extends 'library_app/main.html' %}
{% load static %}

{% block content %}

    <div>{{ object.parent_category }}</div>
    <div>{{ object.title }}</div>
    <div>{{ object.description | safe }}</div>
    <div>{{ object.is_active }}</div>

{% endblock %}

library_app/templates/library_app/unitmodel_form.html
{% extends 'library_app/main.html' %}
{% load static %}

{% block content %}
    <form method="post" action="{% url 'library_app:units_add' %}">
        {% csrf_token %}
        <div>{{ form.parent_category }}</div>
        <div>{{form.title}}</div>
        <div>{{ form.description }}</div>
        <div>{{ form.is_active }}</div>
        <div class="row action-buttons">
                <div class="col-12 col-md-auto">
                    <button type="submit"
                            class="submit-button btn btn-primary btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1"
                            data-loading-text="Loading...">
                        <i class="bx bx-save text-4 me-2"></i> Сохранить
                    </button>
                </div>
                <div class="col-12 col-md-auto px-md-0 mt-3 mt-md-0">
                    <a href="{% url 'library_app:index' %}"
                       class="cancel-button btn btn-light btn-px-4 py-3 border font-weight-semibold text-color-dark text-3">Отменить</a>
                </div>
                <div class="col-12 col-md-auto ms-md-auto mt-3 mt-md-0 ms-auto">
                    <a href="#"
                       class="delete-button btn btn-danger btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1">
                        <i class="bx bx-trash text-4 me-2"></i> Удалить
                    </a>
                </div>
            </div>
    </form>

{% endblock %}

library_app/templates/library_app/unitmodel_list.html
{% extends 'library_app/main.html' %}
{% load static %}

{% block content %}

        <div class="recent_event_area section__padding">
            <div class="container">
                {% for item in object_list %}
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="single_event d-flex align-items-center">

                            <div class="event_info">
                                <a href="{% url 'library_app:units_detail' item.pk %}">
                                    <h4>{{ item.title }}</h4>
                                </a>
                                <p><span> <i class="flaticon-clock"></i> 10:30 pm</span> <span> <i
                                        class="flaticon-calendar"></i> 21Nov 2020 </span> <span> <i
                                        class="flaticon-placeholder"></i> AH Oditoriam</span></p>
                            </div>
                        </div>
                    </div>
                </div>
               {% endfor %}
            </div>
        </div>

{% endblock %}